Create event emitters on adding and removing of transactions for transaction pool - Closes #1013
LiskArchive/lisk-elements pull request #1026
Opened 2019-01-21 15:31 UTC by SargeKhan

### What was the problem?
The transaction pool was not firing any events when transactions were added or removed from the transaction pool.
### How did I fix it?
Created two events which are fired every time transactions are added or removed from the transaction pool. These events are:
1- transactionAdded
2- transactionRemoved

### Review checklist

* The PR resolves #1013 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2019-01-21 20:54 UTC, shuse2 requested changes
looks good, just minor comment

2019-01-21 20:54 UTC, shuse2 commented on packages/lisk-transaction-pool/src/transaction_pool.ts
> +			action: 'addVerifiedRemovedTransactions',
maybe action should be constant and exported?

2019-01-23 09:05 UTC, mitsuaki-u commented on packages/lisk-transaction-pool/src/transaction_pool.ts
> +export const EVENT_ADDED_TRANASCTIONS = 'transactionsAdded';
typo

2019-01-23 09:05 UTC, mitsujutsu commented on packages/lisk-transaction-pool/src/transaction_pool.ts
> +		this.emit(EVENT_ADDED_TRANASCTIONS, {
same as above

2019-01-24 10:32 UTC, shuse2 approved these changes

2019-01-24 10:32 UTC, merged