Make current integration tests pass - Closes #971 and addresses #900
LiskArchive/lisk-elements pull request #1048
Opened 2019-01-28 10:10 UTC by jondubois

### What was the problem?

Core integration tests related to launching a node, connecting to seed peers and doing the first round of discovery were failing. We hadn't yet brought the node into a verifiable working state.

### How did I fix it?

- Fixed bugs in several places; two related to removing event listeners.
- Renamed PeerInfo to P2PPeerInfo since it is exposed publicly by the API (e.g. as part of `getNetworkStatus`).
- Modified `P2PPeerInfo` and `P2PNodeInfo` to be more generic; added an `options` field which can be used to specific custom fields/values on `P2PPeerInfo`/`P2PNodeInfo` objects. This allows the P2P module to support more different kinds of applications.
- Made `selectForConnection` work with `P2PPeerInfo` objects instead of `Peer` objects; it doesn't make sense to filter `Peer` objects if we are yet to connect to them. We should think about other selection functions as well if we want to use `P2PPeerInfo` instead of `Peer`; the `PeerInfo` is much safer to expose to users but may offer less control/flexibility in certain scenarios.
- Made integration tests work with basic discovery scenarios; we still need to add assertions to existing test cases and also add more new test cases; right now the node only does a single round of discovery and this is a problem when all nodes launch at the same time (which is the current situation in integration tests).

### How to test it?

`npm run test:integration`

### Review checklist

* The PR resolves #971 and addresses #900
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2019-01-28 13:05 UTC, shuse2 requested changes
Could you create issue for each `todo` you added?
Also, there is lint problem
```
ERROR: (ordered-imports) /home/lisk/workspace/lisk-elements_PR-1048/packages/lisk-p2p/src/peer_discovery.ts[16, 1]: Import sources within a group must be alphabetized.

ERROR: (ordered-imports) /home/lisk/workspace/lisk-elements_PR-1048/packages/lisk-p2p/src/peer_selection.ts[17, 1]: Import sources within a group must be alphabetized.

ERROR: (ordered-imports) /home/lisk/workspace/lisk-elements_PR-1048/packages/lisk-p2p/src/sanitization.ts[18, 10]: Named imports must be alphabetized.

```

2019-01-28 13:05 UTC, shuse2 commented on packages/lisk-p2p/src/p2p.ts
> +	private _nodeInfo: P2PNodeInfo | undefined;
why is this undefinable?
shouldn't information always supplied in constructor?

2019-01-28 13:05 UTC, shuse2 commented on packages/lisk-p2p/src/sanitization.ts
> + * See the LICENSE file at the top-level directory of this distribution
did this file came back? i think name changed to `validation`

2019-01-28 13:05 UTC, shuse2 commented on packages/lisk-p2p/test/_setup.ts
> +		useFakeTimers: true,
maybe below is cleaner?
```
global.sandbox = sinon.createSandbox({
	useFakeTimers: process.env.USE_REAL_TIMERS !== 'true',
});
```

2019-01-28 16:27 UTC, ishantiw requested changes
Maybe its not a good idea to expose `isTriedPeer` field to the user as its more low level concept of managing peer bucket. Maybe its better if we could have a separate `P2PPeerInfo` without `isTriedPeer` and we can extend it to have a internal PeerInfo definition that will hold more fields related to peer bucket management and selection algo like `isBannedPeer` from LIP

2019-01-28 16:27 UTC, ishantiw commented on packages/lisk-p2p/src/p2p.ts
> +			options: nodeInfo.options,
I think `nodeInfo.options` could be `undefined` as `options` is an optional field in `P2PNodeInfo` so maybe we can have check if it's `undefined`, if it is then atleast assign a blank object

2019-01-28 16:27 UTC, ishantiw commented on packages/lisk-p2p/src/p2p.ts
> +	public get nodeInfo(): P2PNodeInfo | undefined {
I think we can set basic` nodeInfo` in the constructor using values coming with `P2PConfig`, except for field height, which we can default to `0`

2019-01-28 16:27 UTC, ishantiw commented on packages/lisk-p2p/src/peer_pool.ts
> +			peers: this.selectPeers(peerSelectionParams).map((peer: Peer) => {
maybe it's better to move this calculation above and assign to a const variable. Will be easier to debug I guess

2019-01-28 16:27 UTC, ishantiw commented on packages/lisk-p2p/test/unit/peer_selection.ts
>  		describe('get list of n number of good peers', () => {
`get a list`

2019-01-29 08:56 UTC, jondubois commented on packages/lisk-p2p/src/p2p.ts
> +	private _nodeInfo: P2PNodeInfo | undefined;
It's possible to provide nodeInfo to the constructor but then I think we should be clear about how they're provided to the constructor; maybe by adding an explicit `nodeInfo` field. I think this makes sense actually. `nodeInfo` will be information which may be used internally by the node and which should be exposed publicly to other nodes.

2019-01-29 09:25 UTC, jondubois commented
@ishantiw About `isTriedPeer`; that sounds good. We should do this as a separate PR though because otherwise this PR will get huge and it's already addressing too many problems. At least once we've merged this PR we can change stuff and then run the integration tests to make sure that we don't break things.

2019-01-29 09:27 UTC, jondubois commented on packages/lisk-p2p/src/p2p.ts
> +	public get nodeInfo(): P2PNodeInfo | undefined {
I changed it so that the user needs to pass a new `nodeInfo` fields to the P2P constructor. This guarantees that P2PNodeInfo is always defined and is more explicit.

2019-01-29 16:43 UTC, ishantiw approved these changes
Looks good

2019-01-29 16:49 UTC, shuse2 approved these changes

2019-01-29 17:06 UTC, merged