Add missing unit tests for custom errors in lisk-p2p - Closes#1043
LiskArchive/lisk-elements pull request #1049
Opened 2019-01-28 13:08 UTC by ishantiw

### Description

There are some missing test cases for custom error classes in lisk-p2p.
Closes a task in #970

### Review checklist

* The PR resolves #1043 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2019-01-28 13:11 UTC, shuse2 requested changes

2019-01-28 13:11 UTC, shuse2 commented on packages/lisk-p2p/test/unit/errors.ts
> +		const defaultMessage = 'Invalid RPC request error';
prefer const first and let

2019-01-28 13:47 UTC, ishantiw commented
Addressed

2019-01-28 13:47 UTC, shuse2 submitted a review, later dismissed

2019-01-30 09:35 UTC, jondubois approved these changes

2019-01-30 12:33 UTC, shuse2 approved these changes

2019-01-30 12:50 UTC, merged