Change selectPeers function to only handle detailed PeerInfo objects; not live Peer objects Closes#1059
LiskArchive/lisk-elements pull request #1067
Opened 2019-01-31 15:54 UTC by ishantiw

### Description

Currently, the `selectPeers` function accepts and returns a list of `Peer` objects (`ReadonlyArray<Peer>`). We should make the `selectPeers` function in `peer_selection.ts` work with detailed peer info objects instead of live Peer objects.

### Review checklist

* The PR resolves #1059
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2019-02-01 09:16 UTC, shuse2 requested changes

2019-02-01 09:16 UTC, shuse2 commented on packages/lisk-p2p/src/peer.ts
> +	public static constructPeerIdFromPeerInfo(peerInfo: P2PPeerInfo): string {
maybe just export as a function?

2019-02-01 10:27 UTC, jondubois requested changes

2019-02-01 10:27 UTC, jondubois commented on packages/lisk-p2p/src/p2p.ts
> +		const response = await this._peerPool.requestPeer(packet, this._nodeInfo);
We shouldn't pass `this._nodeInfo` as second argument. We should only support a single way of updating the nodeInfo; using `applyNodeInfo`.

Because the `PeerPool` now holds a reference to the latest `_nodeInfo` state internally, you can just use `this. _nodeInfo` from inside the `PeerPool` instead.

2019-02-01 10:27 UTC, jondubois commented on packages/lisk-p2p/src/p2p.ts
> +		this._peerPool.sendToPeers(message, this._nodeInfo);
Similar as previous comment.

2019-02-01 10:27 UTC, jondubois commented on packages/lisk-p2p/src/peer.ts
> +	public static constructPeerIdFromPeerInfo(peerInfo: P2PPeerInfo): string {
If we export as a function then we should do the same for the `Peer.constructPeerId(address, port)` which is now a static method.

Or we can do this in a separate PR because I also rely on the same static method right now for my next PR.

2019-02-01 10:27 UTC, jondubois commented on packages/lisk-p2p/src/peer_pool.ts
> +			lastBlockHeight: nodeInfo.height,
As mentioned in previous comment, you can just use `this._nodeInfo` instead of getting the nodeInfo as a second argument to this function.

2019-02-01 10:27 UTC, jondubois commented on packages/lisk-p2p/src/peer_pool.ts
> +	public sendToPeers(message: P2PMessagePacket, nodeInfo: P2PNodeInfo): void {
Same as previous comment about nodeInfo.

2019-02-01 14:47 UTC, ishantiw commented
comments are addressed

2019-02-02 12:30 UTC, shuse2 submitted a review, later dismissed

2019-02-05 15:24 UTC, shuse2 approved these changes

2019-02-05 15:30 UTC, jondubois approved these changes

2019-02-05 15:31 UTC, merged