Add integration tests for P2P library - Closes #1068
LiskArchive/lisk-elements pull request #1069
Opened 2019-02-01 18:25 UTC by jondubois

### What was the problem?

Missing integration tests.

### How did I fix it?

- Implemented integration test cases.
- Fixed some bugs which were uncovered by the new test cases.

### How to test it?

`npm run test:integration`

### Review checklist

* The PR resolves #1068
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2019-02-02 12:26 UTC, shuse2 requested changes

2019-02-02 12:26 UTC, shuse2 commented on packages/lisk-p2p/src/peer.ts
> +	public static constructPeerId(ipAddress: string, wsPort: number): string {
prefer to make those 2 function as pure function.

2019-02-02 12:26 UTC, shuse2 commented on packages/lisk-p2p/test/integration/p2p.ts
> +			for (const p2p of p2pNodeList) {
we don't need `tslint:disable-next-line` here?

2019-02-04 09:07 UTC, jondubois commented on packages/lisk-p2p/test/integration/p2p.ts
> +			for (const p2p of p2pNodeList) {
For some reason `npm run lint` doesn't seem to mind about this in the integration tests.

2019-02-04 09:25 UTC, jondubois commented
Rebased to fix conflicts.

2019-02-04 12:05 UTC, shuse2 approved these changes

2019-02-04 16:23 UTC, merged