Update error to contain detail info when thrown - Closes#1080
LiskArchive/lisk-elements pull request #1089
Opened 2019-02-11 09:03 UTC by shuse2

### What was the problem?
Error message didn't contain enough information.

### How did I fix it?
Add `toString` method to show more useful information when thrown

### How to test it?
`throw new TransactionError('new message', 'id', 'data-path')`
and see if the message contains all the information.

### Review checklist

* The PR resolves #1080 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2019-02-11 10:03 UTC, mitsuaki-u submitted a review, later dismissed

2019-02-12 09:40 UTC, mitsuaki-u submitted a review, later dismissed

2019-02-12 09:40 UTC, mitsujutsu commented on packages/lisk-transactions/src/errors.ts
> +		const withActial = this.actual ? `${defaultMessage}, actual: ${this.actual}` : defaultMessage;
`Actual`

2019-02-12 11:55 UTC, SargeKhan requested changes

2019-02-12 11:55 UTC, SargeKhan commented on packages/lisk-transactions/src/errors.ts
> +		return `Transaction: ${this.id} failed at ${this.dataPath}: ${
Why don't we add `errors` to `toString` function?

2019-02-12 19:14 UTC, SargeKhan submitted a review, later dismissed

2019-02-13 14:59 UTC, SargeKhan approved these changes

2019-02-13 15:29 UTC, merged