77 hide private methods
LiskArchive/lisk-elements pull request #130
Opened 2017-06-04 22:25 UTC by alepop

Resolve #77 
- Expose private method to another module
- Rewrite tests

2017-06-14 10:59 UTC, toschdev requested changes
Overall, very good implementation of the privateAPI methods. I also like that you have created a new utils file for utility functions. Very good work, keep it up! Just few minor change requests for code format.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
Please do not use semicolons after pure function declarations. We have not done this elsewhere in the codebase so far.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
Semicolon, see above

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 10:59 UTC, Tosch110 commented on lib/api/privateApi.js
> +};
semicolon. s.o.

2017-06-14 11:48 UTC, toschdev submitted a review, later dismissed

2017-06-14 12:42 UTC, toschdev submitted a review, later dismissed

2017-06-27 08:37 UTC, toschdev approved these changes

2017-06-27 08:38 UTC, merged