Return false instead of error in decrypt - Closes #341
LiskArchive/lisk-elements pull request #372
Opened 2017-09-11 14:43 UTC by Tosch110

Closes #341

2017-09-11 15:30 UTC, willclarktech requested changes

2017-09-11 15:30 UTC, willclarktech commented on test/crypto/sign.js
>  		it('should throw on invalid secondary signature', () => {
Test descriptions

2017-09-11 15:30 UTC, willclarktech commented on src/crypto/sign.js
> +	return false;
Yuidoc return types. Do we want to always return a boolean instead of sometimes a boolean, sometimes a string?

2017-09-15 09:32 UTC, Tosch110 commented
New solution in https://github.com/LiskHQ/lisk-js/pull/379

2017-09-15 09:32 UTC, closed without merging