Avoid rounding issues when encoding amount 2^62+3 in test data
LiskArchive/lisk-elements pull request #675
Opened 2018-05-24 09:53 UTC by webmaster128

### What was the problem?

See #669

### How did I fix it?

See code

### How to test it?

Run tests

### Review checklist

* Resolves #669
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the
	[commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2018-05-24 14:25 UTC, willclarktech requested changes
Thanks for the PR! One small request.

2018-05-24 14:31 UTC, webmaster128 commented on test/transactions/utils/get_transaction_bytes.js
> +// a string. Expected encoding: `python3 -c 'print(hex((1<<62)+3))'` with reversed byte order
Hmm, do you have an alternative? I don't think it is trivial how you come from 2^62 + 3 to 0300000000000040. Python has the advantage of native big integers and is available everywhere

2018-05-24 22:31 UTC, webmaster128 commented
Ah well I do not really care – I know how to encode integers. Removed the encoding part of the comment

2018-05-25 10:14 UTC, willclarktech approved these changes

2018-05-25 10:29 UTC, merged