Add function to validate transactions
LiskArchive/lisk-elements pull request #678
Opened 2018-05-31 08:15 UTC by willclarktech

### What was the problem?

We could verify transactions via verifying the signature, but not that they had the right shape. This made it difficult if you e.g. wanted to validate an input was a valid unsigned transaction before asking the user for their passphrase to sign it.

### How did I fix it?

Added a function to validate the schema of a transaction.

This is a WIP - submitting a PR now to get feedback on the general approach as I'm not 100% that it's the right one to take. An alternative would be to use something like z-schema, or to wait until we implement a type system in #417 .

### How to test it?

Create some valid/invalid transactions and try validating them.

### Review checklist

* The PR solves #676 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the
	[commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2018-06-05 20:18 UTC, shuse2 requested changes
Target branch is `development`

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +	return true;
This return value is not parallel.
If we `return true`, i think it's better to have `return false`

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +			'Transaction amount must be a string integer between 0 and 18446744073709551615',
It would be better to use the constant `MAX_TRANSACTION_AMOUNT`

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +	if (![null, undefined].includes(signSignature)) {
Maybe we should decide if we should allow `signSignature != null`

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +		throw new Error('Type 0 transactions must have a fee of 0.1 LSK');
I think this is not only Type 0.

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +	if (typeof asset.data !== 'undefined' && (typeof asset.data !== 'string' || asset.data.length > MAX_TRANSACTION_DATA_BYTES)) {
It would be better to check the asset contents depending on the transaction type

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +		validateAddress(recipientId);
depending on type, it doesn't require `recipientId`

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +	if (![null, undefined].includes(recipientPublicKey)) {
we should check if we should include recipientPublicKey or not depending on transaction type

2018-06-05 20:18 UTC, shuse2 commented on src/transactions/utils/validation.js
> +		typeof amount !== 'string' ||
I think amount should be greater than 0 only if it's type 0

2018-06-06 12:22 UTC, willclarktech commented
Closing for now. We'll revisit this for v1.1.0.

2018-06-06 12:22 UTC, closed without merging