Use discover peers function in p2p - Closes#979
LiskArchive/lisk-elements pull request #991
Opened 2019-01-09 16:04 UTC by ishantiw

### Description

Use discovery in P2P to find new peers. It should take initial peers on which the discovery algo will run and then it will return all the relevant peers based on the algo and add it to `newPeers` list.

* The PR resolves #979 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

2019-01-09 16:07 UTC, shuse2 approved these changes

2019-01-14 08:51 UTC, shuse2 requested changes

2019-01-14 08:51 UTC, shuse2 commented on packages/lisk-p2p/src/p2p.ts
> +		discoveredPeers.map((peerInfo: PeerInfo) => {
This should be `forEach` if it's not mapping

2019-01-14 10:29 UTC, shuse2 approved these changes

2019-01-14 17:20 UTC, ishantiw commented
Rebased and ready for review

2019-01-15 12:58 UTC, jondubois approved these changes
Will need to resolve merge conflicts in https://github.com/LiskHQ/lisk-elements/pull/993/files (if any).

2019-01-15 13:14 UTC, merged